"""Alert model — generated by transaction monitoring, processed by agents."""

import enum

from sqlalchemy import JSON, ForeignKey, String, Text, Uuid
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from aml.db.base import Base, TenantMixin


class AlertSeverity(enum.StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(enum.StrEnum):
    NEW = "new"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    ESCALATED = "escalated"
    FALSE_POSITIVE = "false_positive"


class Alert(TenantMixin, Base):
    """
    An AML alert raised by the monitoring engine or rules.

    Agents consume alerts, investigate them, and produce Cases.
    """

    __tablename__ = "alerts"

    # Tenant FK
    tenant_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("tenants.id"),
        nullable=False,
        index=True,
    )
    tenant: Mapped["Tenant"] = relationship(back_populates="alerts")  # noqa: F821

    # Linked customer
    customer_id: Mapped[str | None] = mapped_column(
        Uuid,
        ForeignKey("customers.id"),
        nullable=True,
        index=True,
    )

    # Alert classification
    alert_type: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    severity: Mapped[AlertSeverity] = mapped_column(
        SAEnum(AlertSeverity, native_enum=False, length=20),
        default=AlertSeverity.MEDIUM,
    )
    status: Mapped[AlertStatus] = mapped_column(
        SAEnum(AlertStatus, native_enum=False, length=20),
        default=AlertStatus.NEW,
        index=True,
    )

    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Structured details for agent consumption
    details: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    def __repr__(self) -> str:
        return f"<Alert {self.alert_type} [{self.severity.value}] {self.status.value}>"
