import operator
from typing import Annotated, Any, TypedDict

from pydantic import BaseModel


class ToolCallResult(BaseModel):
    tool_name: str
    result: str


class AgentState(TypedDict):
    """
    Core state object for the Agent Orchestrator loop.
    This carries the context across nodes.
    """

    alert_id: str
    tenant_id: str
    severity: str

    # Text-based plan generated by the planner node
    plan: str

    # The history of tool invocations performed in this iteration
    executed_tools: Annotated[list[ToolCallResult], operator.add]

    # A generic log of textual messages/insights observed by the agent
    observations: Annotated[list[dict[str, Any]], operator.add]

    # Outcome data structure if the agent decides it is finished
    conclusion: dict[str, Any]
