"""
BM25-based sparse embedding provider.

Generates sparse vectors from text using a lightweight BM25 tokeniser.
No external model is required — tokens are hashed to integer IDs and
weighted by a simplified TF-IDF-like scheme.

This is intentionally self-contained so the project does not need heavy
ML dependencies (like ``milvus-model``) just for sparse embeddings.
"""

import hashlib
import math
import re

import structlog

logger = structlog.get_logger()


class BM25SparseEmbeddingProvider:
    """Sparse embedding provider using BM25-style term weighting.

    Token IDs are generated by hashing normalised terms to positive
    integers.  Weights are computed as ``log(1 + tf)`` where *tf* is
    the in-document term frequency.  This is a simplified BM25 variant
    that works well without a corpus-level IDF table, making it
    suitable for a self-contained sparse retrieval component.
    """

    def __init__(self, *, stop_words: set[str] | None = None) -> None:
        self._stop_words = stop_words or _DEFAULT_STOP_WORDS

    async def embed_sparse(self, text: str) -> dict[int, float]:
        """Generate a sparse vector for a single string."""
        return self._compute_sparse(text)

    async def embed_sparse_batch(self, texts: list[str]) -> list[dict[int, float]]:
        """Generate sparse vectors for multiple strings."""
        return [self._compute_sparse(t) for t in texts]

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _tokenise(self, text: str) -> list[str]:
        """Lowercase, strip non-alphanumeric, remove stop words."""
        tokens = re.findall(r"[a-z0-9]+", text.lower())
        return [t for t in tokens if t not in self._stop_words and len(t) > 1]

    @staticmethod
    def _token_to_id(token: str) -> int:
        """Deterministic hash of a token string to a positive integer.

        Uses the first 8 bytes of SHA-256 to avoid collisions while
        keeping the IDs within a manageable range.
        """
        digest = hashlib.sha256(token.encode()).digest()
        return int.from_bytes(digest[:8], "big")

    def _compute_sparse(self, text: str) -> dict[int, float]:
        tokens = self._tokenise(text)
        if not tokens:
            return {}

        # Term frequency
        tf: dict[str, int] = {}
        for t in tokens:
            tf[t] = tf.get(t, 0) + 1

        # Convert to sparse vector: token_id -> weight
        sparse: dict[int, float] = {}
        for term, count in tf.items():
            token_id = self._token_to_id(term)
            weight = math.log(1.0 + count)
            sparse[token_id] = weight

        return sparse


# Minimal English stop-word list to reduce noise in sparse vectors.
_DEFAULT_STOP_WORDS: set[str] = {
    "a",
    "an",
    "the",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "as",
    "is",
    "it",
    "its",
    "was",
    "are",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "shall",
    "should",
    "may",
    "might",
    "can",
    "could",
    "not",
    "no",
    "nor",
    "so",
    "if",
    "then",
    "than",
    "that",
    "this",
    "these",
    "those",
    "he",
    "she",
    "we",
    "they",
    "you",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "our",
    "their",
    "what",
    "which",
    "who",
    "whom",
    "when",
    "where",
    "why",
    "how",
    "all",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "only",
    "own",
    "same",
    "too",
    "very",
    "just",
    "about",
    "above",
    "after",
    "again",
    "also",
    "any",
    "because",
    "before",
    "between",
    "during",
    "here",
    "into",
    "out",
    "over",
    "under",
    "up",
}
